import React from 'react';
import { useSimulation } from '../context/SimulationContext';
import { Card, StatBox, Button, Badge } from '../components/UI';
import { RevenueChart } from '../components/Charts';
import { DollarSign, TrendingUp, Users, BrainCircuit, AlertOctagon } from 'lucide-react';
import { Methodology } from '../types';

const CEODashboard: React.FC = () => {
  const { company, tasks } = useSimulation();

  const revenueData = [
    { name: 'Jan', revenue: 1000000 },
    { name: 'Feb', revenue: 1100000 },
    { name: 'Mar', revenue: 1050000 },
    { name: 'Apr', revenue: 1250000 },
    { name: 'May', revenue: company.revenue },
  ];

  return (
    <div className="space-y-6">
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        <StatBox label="Annual Run Rate" value={`$${(company.revenue * 12 / 1000000).toFixed(1)}M`} trend="+15%" trendUp />
        <StatBox label="Total Employees" value={company.employees} trend="+4" trendUp />
        <StatBox label="Burn Rate" value={`$${company.burnRate}/day`} trend="-2%" trendUp />
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        <div className="lg:col-span-2">
           <Card title="Revenue Projection" icon={DollarSign}>
             <RevenueChart data={revenueData} />
           </Card>

           <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mt-6">
              <Card title="Active Departments" icon={Users}>
                 <div className="space-y-3">
                    {['Engineering', 'Product', 'Sales', 'Marketing'].map(dept => (
                      <div key={dept} className="flex justify-between items-center p-2 hover:bg-slate-800 rounded transition-colors">
                        <span className="text-sm font-medium text-slate-300">{dept}</span>
                        <Badge color="blue">Active</Badge>
                      </div>
                    ))}
                    <Button variant="outline" className="w-full text-xs mt-2">+ Create Department</Button>
                 </div>
              </Card>

              <Card title="Strategic Risks" icon={AlertOctagon}>
                 <div className="space-y-3">
                   <div className="p-3 bg-rose-950/30 border border-rose-900/50 rounded-lg">
                      <h5 className="text-sm font-bold text-rose-400 flex items-center gap-2">
                        <AlertOctagon size={14} /> AI Over-reliance
                      </h5>
                      <p className="text-xs text-slate-400 mt-1">45% of code generated by AI without sufficient review.</p>
                   </div>
                   <div className="p-3 bg-amber-950/30 border border-amber-900/50 rounded-lg">
                      <h5 className="text-sm font-bold text-amber-400">Market Volatility</h5>
                      <p className="text-xs text-slate-400 mt-1">Client churn increased by 2%.</p>
                   </div>
                 </div>
              </Card>
           </div>
        </div>

        <div className="space-y-6">
           <Card title="Methodology" icon={BrainCircuit}>
             <div className="space-y-4">
               <div className="text-center p-4 bg-slate-900 rounded-lg border border-indigo-500/30">
                 <h3 className="text-xl font-bold text-white">{company.methodology}</h3>
                 <p className="text-xs text-slate-500 mt-1">Current Framework</p>
               </div>
               
               <div className="space-y-2">
                 <label className="text-xs text-slate-400 uppercase font-semibold">Switch Model</label>
                 <div className="grid grid-cols-1 gap-2">
                    {Object.values(Methodology).map(m => (
                      <button key={m} className={`text-left px-3 py-2 text-sm rounded border ${company.methodology === m ? 'bg-indigo-600 border-indigo-500 text-white' : 'bg-slate-800 border-slate-700 text-slate-400 hover:border-slate-500'}`}>
                        {m}
                      </button>
                    ))}
                 </div>
               </div>
             </div>
           </Card>

           <Card title="Profit Simulation">
              <div className="space-y-4">
                <div>
                   <div className="flex justify-between text-xs mb-1">
                     <span className="text-slate-400">Projected Profit</span>
                     <span className="text-emerald-400 font-bold">22%</span>
                   </div>
                   <div className="w-full bg-slate-700 h-2 rounded-full overflow-hidden">
                     <div className="bg-emerald-500 h-full w-[22%]"></div>
                   </div>
                </div>
                
                <div className="pt-4 border-t border-slate-700">
                  <p className="text-xs text-slate-500 mb-2">Simulate Market Shock</p>
                  <input type="range" className="w-full h-2 bg-slate-700 rounded-lg appearance-none cursor-pointer" />
                </div>
              </div>
           </Card>
        </div>
      </div>
    </div>
  );
};

export default CEODashboard;
